Fix some issues
ddlibrary/ddlibrary pull request #293
Opened 2024-02-12 09:43 UTC by azizullahsaeidi

On this PR I have fixed some issues and add Recaptcha v3.

1. Remove facebook sdk
2. Fix GlossaryListTest's namespace 
3. Create .env.example
4. Add subscriber to registration form and add the text on language files
5. Add reCaptcha V3
6. Create RecaptchaRule for validation base on [documentation](https://developers.google.com/recaptcha/docs/verify) 

Note: please create reCaptcha site and secret keys from this [link](https://www.google.com/recaptcha/admin/create)

> Please run `php artisan migrate` , ` composer install` and `npm run production`

2024-02-14 10:16 UTC, uyscuti-wiki requested changes
Thank you Aziz. This looks pretty good to me. Please address the inline comments. Additionally I have a few comments as well.

1. The login, and the contact us forms must be reCAPTCHA protected. 
2. The login page fields appear wonky, which needs to be fixed. 
3. On the register page, move the 'sign in' link from the form to below the header 'Register an account' in smaller text. The text could be - 'Or sign in if you already have an account'. 
![image](https://github.com/ddlibrary/ddlibrary/assets/13994249/2fb9c1e7-a755-4e9c-94a7-5e508bc57069)

Thank you!

2024-02-14 10:16 UTC, uyscuti-wiki commented on resources/views/home.blade.php
> +            <form action="{{ route('subscribe') }}" method="POST">
We want this form to be protected by reCAPTCHA as well.

2024-02-14 10:16 UTC, uyscuti-wiki commented on resources/views/home.blade.php
> +            </form>
If I am being honest, I am not a fan of placing a text field here. Can we remove the text field and change the 'submit' button to a link like the rest of the links? You can redirect users to a different page where we ask their name and email (if not logged in). If they are logged in, auto populate the fields.

2024-02-14 10:19 UTC, uyscuti-wiki commented on database/migrations/2023_12_07_125201_create_subscribers_table.php
> +            $table->string('email')->unique();
Might be worth adding the `user_id` (if available) and `name` as columns.

2024-02-14 10:30 UTC, azizullahsaeidi commented on config/services.php
> +
Yes we should remove it. I will do it. Thanks

2024-02-17 05:45 UTC, uyscuti-wiki commented on lang/en.json
> +}
Please add a newline at EOF here.

2024-02-17 16:06 UTC, uyscuti-wiki approved these changes
Looks great! Thank you Aziz.

2024-02-17 16:06 UTC, merged