Add alert component
ddlibrary/ddlibrary pull request #306
Opened 2024-03-07 11:19 UTC by azizullahsaeidi

1. Create alert message component
2. Add this component on `update user profile `, `Create new resource` and `Add subscribe`

2024-03-18 12:24 UTC, uyscuti-wiki requested changes
Excellent work adding session alerts, Aziz. I have requested some changes. This should be good to go once it is all sorted out. 

While we are on this, let's also make it a practice of adding tests for all the new features we add going forward. Let's start with this PR.

2024-03-18 12:24 UTC, uyscuti-wiki commented on resources/views/users/view_user.blade.php
> +                        </div>
If `status` is anything other than `1`, we can reasonably assume that they won't (or shouldn't rather) be able to login, making the `status` display redundant here. Let's remove this and check if `status` is `1` before allowing them to view this page. 

If it's not `1`, let's log them out.

2024-03-18 12:58 UTC, azizullahsaeidi commented on resources/views/subscribe/index.blade.php
> +                            <p class="text-center">@lang('You subscribed our newsletter.')</p>
Great idea. Thanks

2024-03-18 13:13 UTC, azizullahsaeidi commented on resources/assets/css/ddl.css
>  }
Yes you are right, we should remove it.

2024-03-18 13:22 UTC, azizullahsaeidi commented on resources/views/layouts/search.blade.php
> +        @endif
I have added z-index

2024-03-19 08:11 UTC, uyscuti-wiki requested changes
Thank you Aziz. I am still seeing the alert overlaid upon an existing element. We discussed about how different keys and strings affect the code readability. Please also implement it. Should be good to go then.

2024-03-19 08:11 UTC, uyscuti-wiki commented on resources/views/layouts/search.blade.php
> +        @endif
I still believe the placement is problematic. A block-style display that wouldn't overlap on existing content is the way to go. 

![image](https://github.com/ddlibrary/ddlibrary/assets/13994249/8d057ad7-351b-439c-b525-b70a4c4d1493)

2024-03-19 08:11 UTC, uyscuti-wiki commented on resources/views/layouts/search.blade.php
> +        @endif
Centred on the page if possible.

2024-03-19 08:11 UTC, uyscuti-wiki commented on resources/views/layouts/search.blade.php
> +        @endif
![image](https://github.com/ddlibrary/ddlibrary/assets/13994249/edceaf9e-0037-4379-8c46-135d1abaa26a)

2024-03-19 13:00 UTC, azizullahsaeidi commented on lang/en.json
> +    "Error updating data. Please contact us.": "Error updating data. Please <a href='/contact-us'>contact us</a>."
Removed this code

2024-03-19 13:04 UTC, azizullahsaeidi commented on app/Http/Controllers/UserController.php
> +        ]);
Removed this message

2024-03-19 13:05 UTC, azizullahsaeidi commented on resources/views/layouts/search.blade.php
> +        @endif
Solved this issue

2024-03-19 13:21 UTC, azizullahsaeidi commented on resources/views/subscribe/index.blade.php
> +                                </small>
![image](https://github.com/ddlibrary/ddlibrary/assets/18898699/da129008-635e-4961-92e9-7b647ed98756)

2024-03-19 13:22 UTC, azizullahsaeidi commented on resources/views/subscribe/index.blade.php
> +                            <p class="text-center">@lang('You subscribed our newsletter.')</p>
Removed this section instead we redirect to home page

2024-03-25 17:04 UTC, azizullahsaeidi commented
> Please move the alert on the user page to the top. ![image](https://private-user-images.githubusercontent.com/13994249/316565691-2700c689-87e5-4ae8-b7e9-31cc70838320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzODYwNDMsIm5iZiI6MTcxMTM4NTc0MywicGF0aCI6Ii8xMzk5NDI0OS8zMTY1NjU2OTEtMjcwMGM2ODktODdlNS00YWU4LWI3ZTktMzFjYzcwODM4MzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE2NTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYzE4NTMzZTMxZmE0ZTMzYmJhODY0M2JjYzQ4OGMzYmYxYjcxZWJkY2M1ZjdhNmYxNjBhZGVlZDg3NzcwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7j0Fv3qbx4_isT_6JtjIHpWlT8eSzT0lhz-2fQrOnZQ) and I'll merge this.

It is displaying on the top the page.
![image](https://github.com/ddlibrary/ddlibrary/assets/18898699/90020c2b-d9fe-4505-8b80-0c766f9d1daa)

2024-03-25 17:43 UTC, uyscuti-wiki commented
Not on the header, Aziz. Below 'User Details..' if possible.

2024-03-25 17:50 UTC, azizullahsaeidi commented
> Not on the header, Aziz. Below 'User Details..' if possible.

I added this component only one time, If I move it below the `User Details`, then we need to duplicate the code.

2024-03-26 06:59 UTC, uyscuti-wiki commented
How about below the header then? I just don't like the fact that it's overlapping other elements.

2024-03-27 06:40 UTC, uyscuti-wiki approved these changes
Thank you Aziz. I appreciate your patience during the review.

2024-03-27 06:41 UTC, merged