fix login recaptcha style
ddlibrary/ddlibrary pull request #307
Opened 2024-03-07 11:51 UTC by azizullahsaeidi

2024-03-19 06:12 UTC, uyscuti-wiki requested changes
Thank you Aziz. I've left a few comments for you to consider. The form itself needs to be resized. I think it's too large for a login form: 

![image](https://github.com/ddlibrary/ddlibrary/assets/13994249/9c3959c2-53e2-43cd-b666-daae565e5f71)

Needs to restored to its original size: 

![image](https://github.com/ddlibrary/ddlibrary/assets/13994249/dae3779b-51dc-40ba-899d-efc5a3429211)

2024-03-19 06:12 UTC, uyscuti-wiki commented on resources/views/auth/login.blade.php
> +                                autofocus>
Something I noticed doesn't work is the frontend validation, both here and on the registration form. Could you reinstate the bootstrap validation that was here before?

2024-03-19 10:06 UTC, azizullahsaeidi commented
> Thank you Aziz. I've left a few comments for you to consider. The form itself needs to be resized. I think it's too large for a login form:
> 
> ![image](https://private-user-images.githubusercontent.com/13994249/313941653-9c3959c2-53e2-43cd-b666-daae565e5f71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDI5MzQsIm5iZiI6MTcxMDg0MjYzNCwicGF0aCI6Ii8xMzk5NDI0OS8zMTM5NDE2NTMtOWMzOTU5YzItNTNlMi00M2NkLWI2NjYtZGFhZTU2NWU1ZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEwMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ODI3MDhiYjAyODc1Yjg3NDAyYjA5NjhmYmEwMzhmMDYxNzJmNzUyNGMwMmZjNmY0OGE4Zjc1ZWE2YTdiZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZJHqgqfBzIgB6EEArlTTJ4d-jTCTKh5uIOrjHarHnVg)
> 
> Needs to restored to its original size:
> 
> ![image](https://private-user-images.githubusercontent.com/13994249/313941823-dae3779b-51dc-40ba-899d-efc5a3429211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDI5MzQsIm5iZiI6MTcxMDg0MjYzNCwicGF0aCI6Ii8xMzk5NDI0OS8zMTM5NDE4MjMtZGFlMzc3OWItNTFkYy00MGJhLTg5OWQtZWZjNWEzNDI5MjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEwMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YjJmOWU3NGY5ZWRlMWY1MzJlMDA5MmYxNzdlOThkM2E1NGY2YjY1YjFmY2UxNjRmYmQ3MTExNzRmMDM1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sf2dD9Jvo0J2vXIpQHmknyaqgPp4ml_IbbU4V5T5Tog)

@uyscuti-wiki login getting the correct style after we merge [Add Alert Component](https://github.com/ddlibrary/ddlibrary/pull/306) PR
![image](https://github.com/ddlibrary/ddlibrary/assets/18898699/0ceb56ba-6b5c-44e1-81d6-877e4de27c3f)

2024-03-19 11:01 UTC, azizullahsaeidi commented on resources/views/auth/login.blade.php
> +                                    <span>{{ $errors->first('password') }}</span>
> Although code cleanup is necessary, the reason why `$errors->has('email')` was retained for `password` instead of `email` is to keep the login error field agnostic. This should be evident when you submit the form with wrong credentials. Whichever field is wrong, we don't reveal anything beyond, 'this doesn't match our records'.

@uyscuti-wiki in this case we are getting correct error if user and password or password be incorrect

![Screenshot from 2024-03-19 15-28-56](https://github.com/ddlibrary/ddlibrary/assets/18898699/c44c1ba8-ab54-4567-a54b-565fbf572ea5)

2024-03-27 10:01 UTC, uyscuti-wiki approved these changes
Looks great. Thank you!

2024-03-27 10:01 UTC, merged