Subscriber test
ddlibrary/ddlibrary pull request #308
Opened 2024-03-07 12:14 UTC by azizullahsaeidi

2024-03-27 10:31 UTC, uyscuti-wiki requested changes
Hi Aziz, thank you for your work on this. I am seeing some inconsistencies with how we allow someone to subscribe. More as comments.

2024-03-27 10:31 UTC, uyscuti-wiki commented on app/Models/User.php
> +    }
Duplicate. Check line 75.

2024-03-27 10:31 UTC, uyscuti-wiki commented on routes/web.php
> +});
Why have we removed the `verified` middleware from this route?

2024-03-27 10:31 UTC, uyscuti-wiki commented on tests/Feature/Subscribers/SubscriberTest.php
> +    }
'Authenticated' and 'verified'.

2024-03-27 15:56 UTC, azizullahsaeidi commented on routes/web.php
> +});
We haven't removed it, `verified` was added by previous PR. when I pulled the recent changes I got `verified`

2024-03-27 15:56 UTC, azizullahsaeidi commented on tests/Feature/Subscribers/SubscriberTest.php
> +    }
agree with you. Thank you

2024-03-27 15:57 UTC, azizullahsaeidi commented on app/Models/User.php
> +    }
Removed. Thank you

2024-03-27 16:44 UTC, azizullahsaeidi commented
Dear @uyscuti-wiki please review it again. Thank you

2024-04-16 08:15 UTC, uyscuti-wiki commented on tests/Feature/Subscribers/SubscriberTest.php
> +                'email' => 'azizullahsaeidi@email.com',
Are you certain you want your personal info publicly available?

2024-04-16 08:16 UTC, uyscuti-wiki approved these changes
Looks good to me.

2024-04-18 05:33 UTC, azizullahsaeidi commented on tests/Feature/Subscribers/SubscriberTest.php
> +                'email' => 'azizullahsaeidi@email.com',
Thank you @uyscuti-wiki , I am changing.

2024-04-18 06:27 UTC, merged