Kpi resources
ddlibrary/ddlibrary pull request #327
Opened 2024-04-26 17:50 UTC by azizullahsaeidi

2024-05-29 11:04 UTC, uyscuti-wiki commented
@azizullahsaeidi This looks great overall. Few comments about the design:

- Let's replace these tags with circles with three (or two or one depending on what's supported) colour fills next to the title in the card header ![image](https://github.com/ddlibrary/ddlibrary/assets/13994249/69f2a9d2-93a6-4551-8f9d-4a7c3247d424) 
Next to the filter button, aligned right perhaps, you can signify what each coloured circle means. For instance
● - Date
● - Gender
● - Language
Then, only display the circles that are supported in every card header. 
- Where possible, link resources and filters. 
- Where no data is returned, display '[not available]'.
- Replace 'Resouces base on Language' with 'Total resources by languages'.
- Modify 'Top 10 favorite resources' to 'Top 10 favorited resources'.
- Replace 'Downloaded File Sizes' with 'Total data downloaded'.
- Modify 'Top 10 Authors' to 'Top 10 authors'.
- Modify 'Top 10 Publisher' to 'Top 10 publishers'.

I'll add more as new comments as I continue to review the code. Thanks!

2024-06-10 11:17 UTC, uyscuti-wiki requested changes
Thank you for making the changes. Looks pretty good to me. I have requested some minor changes below. Could we also add unit tests?

2024-06-10 11:17 UTC, uyscuti-wiki commented on app/Traits/DownloadCountTrait.php
> +trait DownloadCountTrait
Has this trait been used anywhere?

2024-06-10 11:17 UTC, uyscuti-wiki commented on app/Traits/GenderTrait.php
> +            'None' => 'None'
Could we stick to lowercase initial character for the keys?

2024-06-10 13:00 UTC, azizullahsaeidi commented on app/Traits/GenderTrait.php
> +            'None' => 'None'
Yes sure. Thank you

2024-06-10 13:01 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceAnalyticsController.php
> +        return view('admin.analytics.resource-analytics.index', compact(['records', 'genders', 'languages', 'reportType', 'totalResources', 'sumOfAllIndividualDownloadedFileSizes', 'authors', 'publis
Removed. They not defined. Thank you Aaron

2024-06-10 13:01 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceAnalyticsController.php
> +        $publishers = $this->getTop10AuthorsOrPublishers($request, 'resource_publishers'); // Get top 10 publishers
Done

2024-06-10 13:01 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceAnalyticsController.php
> +        $authors = $this->getTop10AuthorsOrPublishers($request, 'resource_authors'); // Get top 10 authors
Done

2024-06-10 13:10 UTC, azizullahsaeidi commented
> Thank you for making the changes. Looks pretty good to me. I have requested some minor changes below. Could we also add unit tests?

@uyscuti-wiki if you agree, let me write the test in a separate PR.

2024-06-10 16:22 UTC, uyscuti-wiki commented on app/Traits/DownloadCountTrait.php
> +trait DownloadCountTrait
@azizullahsaeidi could you clarify?

2024-06-10 17:29 UTC, azizullahsaeidi commented on app/Traits/DownloadCountTrait.php
> +trait DownloadCountTrait
@uyscuti-wiki  I already deleted this trait.

2024-06-11 07:08 UTC, uyscuti-wiki approved these changes
Looks great! Thank you for your efforts, Aziz.

2024-06-11 07:08 UTC, merged