Kpi user
ddlibrary/ddlibrary pull request #328
Opened 2024-04-30 15:10 UTC by azizullahsaeidi

Please run below command
`
php artisan migrate --path=/database/migrations/2024_04_30_142706_add_provider_to_users_table.php
`

2024-06-12 13:20 UTC, uyscuti-wiki requested changes
Looks good. I've left some comments to improve some aspects of the code.

2024-06-12 13:57 UTC, uyscuti-wiki commented on routes/web.php
> +    Route::get('admin/user-analytics',  [UserAnalyticsController::class, 'index'])->middleware('admin');
Let's also unify the routes for analytics under `admin/analytics/users` and `admin/analytics/resources`.

2024-06-12 17:58 UTC, azizullahsaeidi commented on .env.example
Removed

2024-06-12 17:59 UTC, azizullahsaeidi commented on app/Http/Controllers/UserAnalyticsController.php
> +    private function getTotalUsersBaseOnRole($request): Collection
Done

2024-06-12 18:01 UTC, azizullahsaeidi commented on app/Http/Controllers/UserAnalyticsController.php
> +    private function getTotalUsersBaseOnRegistrationSource($request, $providerName = null): float
Renamed

2024-06-12 18:02 UTC, azizullahsaeidi commented on app/Http/Controllers/UserAnalyticsController.php
> +    private function getTotalUsersBaseOnGender($request): Collection
Done

2024-06-12 18:03 UTC, azizullahsaeidi commented on resources/views/admin/analytics/users/index.blade.php
> +                            <label>From Date</label>
Done

2024-06-12 18:08 UTC, azizullahsaeidi commented on resources/views/admin/analytics/users/index.blade.php
> +                                        @forelse ($top10ActiveUsers as $top10ActiveUser)
Done

2024-06-12 18:09 UTC, azizullahsaeidi commented on resources/views/admin/analytics/users/index.blade.php
> +                                                        {{ number_format($top10ActiveUser->activity_count) }}
Done

2024-06-12 18:12 UTC, azizullahsaeidi commented on config/services.php
> +        'redirect' => env('GOOGLE_REDIRECT', 'https://library.darakhtdanesh.org/login/google/callback/'),
We have default value for it. `'redirect' => 'https://library.darakhtdanesh.org/login/google/callback/',`

2024-06-12 18:12 UTC, azizullahsaeidi commented on resources/views/admin/analytics/users/index.blade.php
> +                                <div class="card-header">List the total admins/managers/translators. </div>
Done

2024-06-12 18:20 UTC, azizullahsaeidi commented on routes/web.php
> +    Route::get('admin/user-analytics',  [UserAnalyticsController::class, 'index'])->middleware('admin');
Thank you, done.

2024-06-12 18:33 UTC, azizullahsaeidi commented on app/Http/Controllers/UserAnalyticsController.php
> +        return Role::withCount([
Done

2024-06-14 09:39 UTC, uyscuti-wiki commented on resources/views/admin/analytics/users/index.blade.php
> +                                                        {{ number_format($top10ActiveUser->activity_count) }}
@azizullahsaeidi I meant just the `activity_count`, not the entire dataset.

2024-06-14 09:47 UTC, uyscuti-wiki commented on resources/views/admin/analytics/users/index.blade.php
> +                                <div class="card-header">Total users base on registration source </div>
@azizullahsaeidi please fix this.

2024-06-14 09:49 UTC, uyscuti-wiki commented on resources/views/admin/analytics/users/index.blade.php
> +                                                        {{ number_format($top10ActiveUser->activity_count) }}
We need the top 10 active users data, just not the numbers against them.

2024-06-14 13:57 UTC, azizullahsaeidi commented on resources/views/admin/analytics/users/index.blade.php
> +                                <div class="card-header">Total users base on registration source </div>
Done

2024-06-17 07:11 UTC, uyscuti-wiki approved these changes
Looks great, thank you Aziz!

2024-06-17 07:13 UTC, merged