Change abstract field to textarea
ddlibrary/ddlibrary pull request #351
Opened 2024-09-03 10:57 UTC by azizullahsaeidi

1. Remove CKEditor from abstract field
2. Add resource image on ResourceStepOne
3. Display resource image on resource list and resource details if uploaded
4. Validate resource image
5. Write test for Resource step-one

2025-01-15 16:40 UTC, uyscuti-wiki requested changes
Thank you so much for working on this Aziz. This is a large PR and would have taken significant time and effort on your part. 

I have completed an initial review and will wait for you to implement the changes and (or) respond to questions. I'll take another pass at the code shortly after.

2025-01-15 16:40 UTC, uyscuti-wiki commented on resources/views/admin/resource-images/cropper.blade.php
> +        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css" />
Can we add a checksum here?

2025-01-15 16:40 UTC, uyscuti-wiki commented on resources/views/admin/resource-images/index.blade.php
> +                            <input type="text" value="{{ request()->search }}" placeholder="Please search..."
"Begin typing here to search for an image".

2025-01-15 16:40 UTC, uyscuti-wiki commented on resources/views/resources/partial/file-list.blade.php
> +</style>
Is there a particular reason these styles cannot be included in `ddl.css`?

2025-01-15 16:40 UTC, uyscuti-wiki commented on resources/views/resources/resources_add_step1.blade.php
> +@endpush
Same here. Can these styles not be added to `ddl.css`?

2025-01-15 16:40 UTC, uyscuti-wiki commented on resources/views/resources/resources_add_step1.blade.php
>      </script>
`ddl.js` would be a better place for this, wouldn't it?

2025-01-16 12:39 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceFileController.php
> +        Storage::disk('s3')->put($path, file_get_contents($file));
Do we not use S3 anymore?

2025-01-16 12:45 UTC, azizullahsaeidi commented on resources/views/resources/partial/file-list.blade.php
> +</style>
these style are used only in this file. if you suggest I can add it to ddl.css

2025-01-16 12:47 UTC, azizullahsaeidi commented on resources/views/resources/partial/file-list.blade.php
> +</style>
I will move it to ddl.css. Thank you

2025-01-17 07:26 UTC, uyscuti-wiki commented on app/Http/Controllers/ResourceFileController.php
> +        Storage::disk('s3')->put($path, file_get_contents($file));
Only for resource attachments. We need to do some housekeeping tasks before we begin to store our files there.

2025-02-25 07:02 UTC, azizullahsaeidi commented on resources/views/resources/resources_add_step1.blade.php
>      </script>
I created two new files, resource.js and resource.css. we are using only in one file.

2025-03-13 05:13 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceFileController.php
> +        // Store the thumbnail in S3
I removed the comments

2025-03-13 05:14 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceFileController.php
> +        // Store the file in S3
Removed the comment. Thank you

2025-03-20 13:38 UTC, azizullahsaeidi commented on app/Http/Controllers/ResourceFileController.php
> +            'uuid' => Str::uuid(),
Dear Aaron,
We are using the file ID in the new resource. If we use the file ID directly, there is a possibility that a user might change it during the upload process. However, since users cannot change the UUID, I added the UUID alongside the ID for increased security and integrity.

2025-03-25 15:08 UTC, azizullahsaeidi commented on resources/views/admin/resource-images/cropper.blade.php
> +                    <i class="fa fa-table"></i> Crop the Image
Done, Thanks

2025-04-09 14:20 UTC, uyscuti-wiki approved these changes
Looks great! Thank you, Aziz.

2025-04-09 14:21 UTC, merged

2025-04-10 08:18 UTC, uyscuti-wiki commented
Please open this PR again @azizullahsaeidi. we'll test it on staging first.